### ISSUE TITLE
Code Lab Feedback

### ISSUE THREAD

**Issue by KatieMFritz** [KatieMFritz/codelab-sinatra-tdd-helper-methods#2]
Hey @chrisvfritz, can you take a look at this? It's [hosted here](https://young-beyond-9564.herokuapp.com/) and meets the following [project](http://lansingcodelab.com/lessons/sinatra-tdd-helper-methods/1) criteria:
- [x] After creating and downloading your repository, follow [the steps in the README](https://github.com/chrisvfritz/codelab-sinatra-tdd-helper-methods#readme) to get tests passing for the first 3 helper methods [in `helpers/methods_practice_helpers.rb`](https://github.com/chrisvfritz/codelab-sinatra-tdd-helper-methods/blob/master/helpers/methods_practice_helpers.rb)

**Comment by KatieMFritz** [comment]
@chrisvfritz, I yearn for a ship-it squirrel...

**Comment by chrisvfritz** [comment]
Looks good! Only thing to fix is [the indentation](https://github.com/katiemfritz/codelab-sinatra-tdd-helper-methods/blob/master/helpers/methods_practice_helpers.rb).

**Comment by KatieMFritz** [comment]
Oops. Should be fixed now.

**Comment by chrisvfritz** [comment]
Magnifique! :shipit:
